<a href="https://colab.research.google.com/github/songpont/report/blob/master/workshop_14Dec2023_dataprep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
import pandas as pd
# Specify the path to your file
file_path = '/content/drive/MyDrive/PM_esan/Fire_Source_2012-2023Nov/03_Yearly_ADM_LU/2013_adm_LU.csv' # Change 'your_file.csv' to your file's name

# Read the file into a DataFrame
df1 = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
df1.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,daynight,type,Year,TAM_NAM_T,AMPHOE_T,AMPHOE_E,PROV_NAM_T,PROV_NAM_E,LUL1_CODE,LUL2_CODE
0,16.037905,104.075516,336.31,0.39,0.36,2013/01/20,618,N,VIIRS,n,...,D,0,2013,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,M,M1
1,15.993228,104.105576,335.04,0.39,0.36,2013/02/05,618,N,VIIRS,n,...,D,0,2013,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A1
2,16.053541,104.096535,335.68,0.48,0.40,2013/02/06,600,N,VIIRS,n,...,D,0,2013,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A1
3,16.052341,104.097794,333.97,0.48,0.40,2013/02/06,600,N,VIIRS,n,...,D,0,2013,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A2
4,16.067593,104.087807,335.17,0.49,0.49,2013/02/12,548,N,VIIRS,n,...,D,0,2013,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A2

In [ ]:
df1

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,daynight,type,Year,TAM_NAM_T,AMPHOE_T,AMPHOE_E,PROV_NAM_T,PROV_NAM_E,LUL1_CODE,LUL2_CODE
0,16.037905,104.075516,336.31,0.39,0.36,2013/01/20,618,N,VIIRS,n,...,D,0,2013,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,M,M1
1,15.993228,104.105576,335.04,0.39,0.36,2013/02/05,618,N,VIIRS,n,...,D,0,2013,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A1
2,16.053541,104.096535,335.68,0.48,0.40,2013/02/06,600,N,VIIRS,n,...,D,0,2013,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A1
3,16.052341,104.097794,333.97,0.48,0.40,2013/02/06,600,N,VIIRS,n,...,D,0,2013,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A2
4,16.067593,104.087807,335.17,0.49,0.49,2013/02/12,548,N,VIIRS,n,...,D,0,2013,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61028,18.219433,103.938828,306.11,0.39,0.36,2013/04/11,1830,N,VIIRS,n,...,N,0,2013,ต.บุ่งคล้า,อ.บุ่งคล้า,Amphoe Bungkha,บึงกาฬ,Bung Kan,F,F1
61029,18.225517,103.932045,302.50,0.39,0.36,2013/04/11,1830,N,VIIRS,n,...,N,0,2013,ต.บุ่งคล้า,อ.บุ่งคล้า,Amphoe Bungkha,บึงกาฬ,Bung Kan,F,F1
61030,18.284437,103.975548,333.73,0.38,0.36,2013/04/21,612,N,VIIRS,n,...,D,0,2013,ต.บุ่งคล้า,อ.บุ่งคล้า,Amphoe Bungkha,บึงกาฬ,Bung Kan,M,M1
61031,18.321087,103.646065,339.35,0.38,0.36,2013/02/16,612,N,VIIRS,n,...,D,0,2013,ต.โนนสมบูรณ์,อ.เมืองบึงกาฬ,Amphoe Muang Bung Kan,บึงกาฬ,Bung Kan,A,A1
61032,18.308784,103.654938,331.85,0.41,0.37,2013/11/26,612,N,VIIRS,n,...,D,3,2013,ต.โนนสมบูรณ์,อ.เมืองบึงกาฬ,Amphoe Muang Bung Kan,บึงกาฬ,Bung Kan,A,A1

In [ ]:
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61033 entries, 0 to 61032
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   latitude    61033 non-null  float64
 1   longitude   61033 non-null  float64
 2   brightness  61033 non-null  float64
 3   scan        61033 non-null  float64
 4   track       61033 non-null  float64
 5   acq_date    61033 non-null  object
 6   acq_time    61033 non-null  int64
 7   satellite   61033 non-null  object
 8   instrument  61033 non-null  object
 9   confidence  61033 non-null  object
 10  version     61033 non-null  int64
 11  bright_t31  61033 non-null  float64
 12  frp         61033 non-null  float64
 13  daynight    61033 non-null  object
 14  type        61033 non-null  int64
 15  Year        61033 non-null  int64
 16  TAM_NAM_T   61033 non-null  object
 17  AMPHOE_T    61033 non-null  object
 18  AMPHOE_E    61033 non-null  object
 19  PROV_NAM_T  61033 non-null  object
 20  PROV_NAM_E  61033 non-null  object
 21  LUL1_CODE   61033 non-null  object
 22  LUL2_CODE   61033 non-null  object
dtypes: float64(7), int64(4), object(12)
memory usage: 10.7+ MB
None

In [ ]:
print (df['Year'].value_counts())

2022    15126
Name: Year, dtype: int64

concat ทุกไฟล์ใน folder **ควรแน่ใจว่าไม่มีไฟล์อื่นๆใน folder**

In [ ]:
#import pandas as pd
import os
import glob

# Define the path to the folder containing your CSV files
folder_path = '/content/drive/My Drive/PM_esan/Fire_Source_2012-2023Nov/03_Yearly_ADM_LU'  # Replace with your folder path
os.chdir(folder_path)

# Create a list of all CSV files in the folder
file_list = glob.glob('*.csv')

# Initialize an empty list to store DataFrames
dfs = []

# Loop through the files, read each file as a DataFrame, and append it to the list
for file in file_list:
    df = pd.read_csv(file)
    dfs.append(df)

# Concatenate all DataFrames in the list
combined_df = pd.concat(dfs, ignore_index=True)

# Display the first few rows of the combined DataFrame
combined_df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,daynight,type,Year,TAM_NAM_T,AMPHOE_T,AMPHOE_E,PROV_NAM_T,PROV_NAM_E,LUL1_CODE,LUL2_CODE
0,16.04633,104.05120,312.16,0.42,0.38,2023/02/28,1849,N,VIIRS,n,...,N,NaN,2023,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A2
1,16.01995,104.05153,302.58,0.66,0.73,2023/03/03,1934,N,VIIRS,n,...,N,NaN,2023,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,M,M1
2,16.05333,104.08307,348.88,0.43,0.38,2023/03/10,631,N,VIIRS,n,...,D,NaN,2023,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A2
3,16.02009,104.09893,336.05,0.34,0.56,2023/03/30,657,N,VIIRS,n,...,D,NaN,2023,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A1
4,16.02532,104.09833,356.00,0.34,0.56,2023/03/30,657,N,VIIRS,n,...,D,NaN,2023,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A3

In [ ]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486962 entries, 0 to 486961
Data columns (total 23 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   latitude    486962 non-null  float64
 1   longitude   486962 non-null  float64
 2   brightness  486962 non-null  float64
 3   scan        486962 non-null  float64
 4   track       486962 non-null  float64
 5   acq_date    486962 non-null  object
 6   acq_time    486962 non-null  int64
 7   satellite   486962 non-null  object
 8   instrument  486962 non-null  object
 9   confidence  486962 non-null  object
 10  version     486962 non-null  object
 11  bright_t31  486962 non-null  float64
 12  frp         486962 non-null  float64
 13  daynight    486962 non-null  object
 14  type        453647 non-null  float64
 15  Year        486962 non-null  int64
 16  TAM_NAM_T   486962 non-null  object
 17  AMPHOE_T    486962 non-null  object
 18  AMPHOE_E    486962 non-null  object
 19  PROV_NAM_T  486962 non-null  object
 20  PROV_NAM_E  486962 non-null  object
 21  LUL1_CODE   486962 non-null  object
 22  LUL2_CODE   486962 non-null  object
dtypes: float64(8), int64(2), object(13)
memory usage: 85.5+ MB

In [ ]:
combined_df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,daynight,type,Year,TAM_NAM_T,AMPHOE_T,AMPHOE_E,PROV_NAM_T,PROV_NAM_E,LUL1_CODE,LUL2_CODE
0,16.04633,104.05120,312.16,0.42,0.38,2023/02/28,1849,N,VIIRS,n,...,N,NaN,2023,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A2
1,16.01995,104.05153,302.58,0.66,0.73,2023/03/03,1934,N,VIIRS,n,...,N,NaN,2023,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,M,M1
2,16.05333,104.08307,348.88,0.43,0.38,2023/03/10,631,N,VIIRS,n,...,D,NaN,2023,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A2
3,16.02009,104.09893,336.05,0.34,0.56,2023/03/30,657,N,VIIRS,n,...,D,NaN,2023,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A1
4,16.02532,104.09833,356.00,0.34,0.56,2023/03/30,657,N,VIIRS,n,...,D,NaN,2023,ต.ภูเงิน,อ.เสลภูมิ,Amphoe Sela Phum,ร้อยเอ็ด,Roi Et,A,A3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486957,18.22189,103.71188,301.16,0.45,0.39,2022/12/15,1855,N,VIIRS,n,...,N,NaN,2022,ต.โนนสมบูรณ์,อ.เมืองบึงกาฬ,Amphoe Muang Bung Kan,บึงกาฬ,Bung Kan,A,A1
486958,18.22325,103.70860,308.40,0.40,0.37,2022/12/16,1836,N,VIIRS,n,...,N,NaN,2022,ต.โนนสมบูรณ์,อ.เมืองบึงกาฬ,Amphoe Muang Bung Kan,บึงกาฬ,Bung Kan,A,A3
486959,18.22201,103.71094,309.61,0.55,0.42,2022/12/20,1902,N,VIIRS,n,...,N,NaN,2022,ต.โนนสมบูรณ์,อ.เมืองบึงกาฬ,Amphoe Muang Bung Kan,บึงกาฬ,Bung Kan,A,A3
486960,18.22198,103.70915,311.11,0.55,0.42,2022/12/20,1902,N,VIIRS,n,...,N,NaN,2022,ต.โนนสมบูรณ์,อ.เมืองบึงกาฬ,Amphoe Muang Bung Kan,บึงกาฬ,Bung Kan,A,A3
486961,18.27301,103.34790,330.60,0.39,0.36,2022/03/18,618,N,VIIRS,n,...,D,0.0,2022,ต.โนนศิลา,อ.ปากคาด,Amphoe Pak Khat,บึงกาฬ,Bung Kan,A,A3

In [ ]:
print (combined_df['Year'].value_counts())

2016    61869
2013    61033
2019    56930
2015    51020
2020    43311
2014    43303
2018    34832
2012    32288
2017    32063
2023    31683
2021    23504
2022    15126
Name: Year, dtype: int64

In [ ]:
print (combined_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486962 entries, 0 to 486961
Data columns (total 23 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   latitude    486962 non-null  float64
 1   longitude   486962 non-null  float64
 2   brightness  486962 non-null  float64
 3   scan        486962 non-null  float64
 4   track       486962 non-null  float64
 5   acq_date    486962 non-null  object
 6   acq_time    486962 non-null  int64
 7   satellite   486962 non-null  object
 8   instrument  486962 non-null  object
 9   confidence  486962 non-null  object
 10  version     486962 non-null  object
 11  bright_t31  486962 non-null  float64
 12  frp         486962 non-null  float64
 13  daynight    486962 non-null  object
 14  type        453647 non-null  float64
 15  Year        486962 non-null  int64
 16  TAM_NAM_T   486962 non-null  object
 17  AMPHOE_T    486962 non-null  object
 18  AMPHOE_E    486962 non-null  object
 19  PROV_NAM_T  486962 non-null  object
 20  PROV_NAM_E  486962 non-null  object
 21  LUL1_CODE   486962 non-null  object
 22  LUL2_CODE   486962 non-null  object
dtypes: float64(8), int64(2), object(13)
memory usage: 85.5+ MB
None

In [ ]:
combined_df.drop('type',axis = 1,inplace = True)

In [ ]:
combined_df.columns

Index(['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date',
       'acq_time', 'satellite', 'instrument', 'confidence', 'version',
       'bright_t31', 'frp', 'daynight', 'Year', 'TAM_NAM_T', 'AMPHOE_T',
       'AMPHOE_E', 'PROV_NAM_T', 'PROV_NAM_E', 'LUL1_CODE', 'LUL2_CODE'],
      dtype='object')

In [ ]:
# Export the DataFrame to a CSV file
combined_df.to_csv('combined_data.csv', index=False)